spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}

ncp:
  object-storage:
    access-key: ${OBJECT_STORAGE_ACCESS_KEY}
    secret-key: ${OBJECT_STORAGE_SECRET_KEY}
    region: ${OBJECT_STORAGE_REGION}
    endpoint: ${OBJECT_STORAGE_ENDPOINT}
    bucket-name: ${OBJECT_STORAGE_BUCKET_NAME}

test:
  mainImageUrl: ${IMAGE_MAIN_TEST}
  detailImageUrl: ${IMAGE_DETAIL_TEST}
