spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pick?serverTimezone=UTC
    username: root
    password: wnswk02
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
