DROP TABLE IF EXISTS member;
CREATE TABLE member (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(20) NOT NULL,
    nickname VARCHAR(15) UNIQUE NOT NULL,
    address VARCHAR(50) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    member_type VARCHAR(10) NOT NULL,
    created_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_dt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT member_type CHECK (member_type IN ('CUSTOMER', 'SELLER', 'ADMIN'))
);
